"""Add stripe_payment_source_id to User model

Revision ID: 12d8621d51f4
Revises: 42344defa540
Create Date: 2025-07-02 16:55:39.001372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d8621d51f4'
down_revision = '42344defa540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_source_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stripe_payment_source_id')

    # ### end Alembic commands ###
