"""Add price and unlock models for paid videos

Revision ID: 42344defa540
Revises: 7b87fb78d79e
Create Date: 2025-07-02 16:18:37.394869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42344defa540'
down_revision = '7b87fb78d79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_video_unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video_unlock')
    )
    with op.batch_alter_table('user_video_unlocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_video_unlocks_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=False)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_paid_unlock', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('is_paid_unlock')
        batch_op.drop_column('price')

    with op.batch_alter_table('user_video_unlocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_video_unlocks_stripe_payment_intent_id'))

    op.drop_table('user_video_unlocks')
    # ### end Alembic commands ###
