"""Add is_public to Video model

Revision ID: 7b87fb78d79e
Revises: cdc5ca307095
Create Date: 2025-07-02 11:47:41.928992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b87fb78d79e'
down_revision = 'cdc5ca307095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
